#!/bin/bash

# shell script that simulate gentcos process

echo "THIS gentcos script is for testing TcosConfig !!!!"

echo
echo

get_line() {
head -$1 /etc/tcos/templates/tcosconfig.conf | tail -1
}

NUM=$(cat /etc/tcos/templates/tcosconfig.conf| wc -l)

echo "-------------------------------------------------------"
for i in $(seq $NUM ); do
  echo $(get_line $i)
done
echo "-------------------------------------------------------"


sleep 2

echo "finishing..."
sleep 1
echo "done"

exit 0
