.\"Created with GNOME Manpages Editor Wizard
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH tcosconfig 1 "Mar 11, 2007" "tcosconfig man page"

.SH NAME
tcosconfig \- TCOS tool to create and personalize initramfs network boot files

.SH DESCRIPTION

.PP
\fBtcosconfig\fP is a python + gtk2 gui for gentcos command


.SH OPTIONS
.B [no options]
 With no options will exec TcosConfig in normal mode

.B --debug
 Show verbose output when running

.B --help
 Some usage help about tcosconfig


.SH BUGS
Contact Mario Izquierdo <mariodebian@gmail.com>

Homepage: http://www.tcosproject.org

.SH SEE ALSO
gentcos(1)

.SH AUTHOR
Mario Izquierdo (mariodebian) <mariodebian@gmail.com>
